---

before_install:
  - sudo apt-get update
  - sudo echo "deb http://archive.ubuntu.com/ubuntu release-backports main restricted universe multiverse" > /etc/apt/sources.list.d/backports.list
  - sudo apt-get update
  - apt-get install jq

script:

  - 'jq'
